server:
  port: 9090

logrus:
  time-format: 2006-01-02 15:04:05
  tty-discard: false
  graylog:
    enable: false
    host: 127.0.0.1
    port: 5555
    extra:
      tag: abc
      image: 123

oracle:
  user: abc
  password: enc(ad62d1c3882f86965306f0013cd37ac330c7ad7c1c)
  datasource: 127.0.0.1:1521/testdb

mysql:
  user: root
  password: 123456
  datasource: tcp(127.0.0.1:3306)/t1

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  db: testdb
  ssl-mode: disable

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: enc(436c7849214555123a97c132730d70538e23554583ed70be)
  read-timeout: 20 # seconds
  write-timeout: 20 # seconds

rocketmq:
  addrs:
    - 127.0.0.1:9876
  # retry: 2
  access-key: 123456
  secret-key: 654321

tablestore:
  end-point: 127.0.0.1
  instance-name: abc
  access-key-id: 123456
  access-key-secret: 654321

crontab:
  enable: true
  log-discard: false
  specs:
    demo1: "*/1 * * * * ?"
    hello: "*/5 * * * * ?"
    demo3: "*/1 * * * * ?"
    
reserved:
  key: 123
  str: hello
  urls:
    - 127.0.0.1:9090
    - 127.0.0.1:9091
  complex:
    a: 1
    b: 2
  a-b: text_2
  a_b: text_1
  AB: AB
  a_B: aB

pg:
  addr: 127.0.0.1:5432
  user: pg
  password: 123456

maria:
  addr: 127.0.0.1:3306
  user: maria
  password: 654321

logic:
  api: http://127.0.0.1:9092/logic
  names:
    - jack
    - rose
    - tom
