server:
  port: 9090

logrus:
  time-format: 2006-01-02 15:04:05
  tty-discard: false
  graylog:
    enable: true
    host: 127.0.0.1
    port: 5555
    extra:
      tag: abc
      image: 123

oracle:
  driver: godror
  user: abc
  password: enc(ad62d1c3882f86965306f0013cd37ac330c7ad7c1c)
  datasource: 127.0.0.1:1521/testdb

mysql:
  driver: mysql
  user: abc
  password: enc(dfdf920e95c3565b95749dd03e788fd486f489e72094)
  datasource: tcp(127.0.0.1:3306)/testdb

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  db: testdb
  ssl-mode: disable

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: enc(436c7849214555123a97c132730d70538e23554583ed70be)

rocket-mq:
  addr:
    - 127.0.0.1:9876
  retry: 2
  access-key: 123456
  secret-key: 654321

table-store:
  end-point: 127.0.0.1
  instance-name: abc
  access-key-id: 123456
  access-key-secret: 654321

crontab:
  demo1: "*/1 * * * * ?"
  hello: "*/5 * * * * ?"
  demo3: "*/1 * * * * ?"

secure:
  key: 6c841a6c8b9e3b42dfd30dc950da0382

reserved:
  key: 123
  str: hello
  urls:
    - 127.0.0.1:9090
    - 127.0.0.1:9091
  complex:
    a: 1
    b: 2
  a-b: text_2
  a_b: text_1
  AB: AB
  a_B: aB

pg:
  addr: 127.0.0.1:5432
  user: pg
  password: 123456

maria:
  addr: 127.0.0.1:3306
  user: maria
  password: 654321

logic:
  api: http://127.0.0.1:9092/logic
  names:
    - jack
    - rose
    - tom